;
; Copyright (c) 2020 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: Apache-2.0
;

Upload = {
	? "image" => uint,
	? "len" => uint,
	  "off" => uint,
	? "sha" => bstr,
	? "data" => bstr,
	? "upgrade" => bool,
}
